server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化最大，最小
    initialSize: 1
    minIdle: 1
    maxActive: 20
    #等待超时时间
    maxWait: 60000
    #多久一次检测
    timeBetweenEvictionRunsMillis: 60000
    #最小生存时间
    minEvictableIdleTimeMillis: 30000
    # oracle必须这样配置检查，不了会报检查错误 验证数据库连接的查询语句
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache 并制定每个连接上的PASCache的大小
    #减少创建游标的数量。复用游标
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉监控界面sql无法统计,wall用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true
  redis:
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-idle: 100
            min-idle: 1
            max-active: 1000
            max-wait: -1
mybatis:
  #扫描dao xml
  mapper-locations:
    - mapper/*/*.xml
  #实体类别名
  type-aliases-package:
    com.springboot.entity

  # 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
